services:
  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - dynamodb
    volumes:
      - ./app:/app
    restart: always

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb_local
    user: "0:0" # se ocupa root solo porque es ambiente de prueba
    ports:
      - "8001:8000"
    command:
      - "-jar"
      - "DynamoDBLocal.jar"
      - "-sharedDb"
      - "-dbPath"
      - "/home/dynamodblocal/data"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    restart: always

volumes:
  dynamodb_data:
